version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./db/init-databases.sh:/docker-entrypoint-initdb.d/init-tora-databases.sh
    ports:
      - "5432:5432"
