server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/main}
    username: ${DATASOURCE_USERNAME:main}
    password: ${DATASOURCE_PASSWORD:main}

  flyway:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/main}
    driver-class-name: org.postgresql.Driver
    user: ${DATASOURCE_USERNAME:main}
    password: ${DATASOURCE_PASSWORD:main}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  kafka:
    bootstrap-servers: localhost:29092
    pay-log:
      topic:
        name: paylog

paymentIntegration:
  accessToken: asd
  url: ${PAYMENT_INTEGRATION_URL:http://localhost:9090/api/v1/payment/}

#logging:
#  level:
#    com:
#      atomikos: DEBUG

logging:
  level:
    org:
      springframework:
        security: debug

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks


