spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:54320/postgres
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:54320/postgres
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: postgres
    enabled: true
