server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/main}
    username: ${DATASOURCE_USERNAME:main}
    password: ${DATASOURCE_PASSWORD:main}

  flyway:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/main}
    driver-class-name: org.postgresql.Driver
    user: ${DATASOURCE_USERNAME:main}
    password: ${DATASOURCE_PASSWORD:main}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

paymentIntegration:
  accessToken: asd
  url: ${PAYMENT_INTEGRATION_URL:http://localhost:9090/api/v1/payment/}

#logging:
#  level:
#    com:
#      atomikos: DEBUG

logging:
  level:
    org:
      springframework:
        security: debug
