server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${DATASOURCE_USERNAME:s309681}
    password: ${DATASOURCE_PASSWORD}

  flyway:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    driver-class-name: org.postgresql.Driver
    user: ${DATASOURCE_USERNAME:s309681}
    password: ${DATASOURCE_PASSWORD}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

paymentIntegration:
  accessToken: asd
  url: ${PAYMENT_INTEGRATION_URL:http://localhost:9090/api/v1/payment/}
