server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}

  flyway:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/postgres}
    driver-class-name: org.postgresql.Driver
    user: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  mvc:
    log-request-details:
      true

paymentIntegration:
  accessToken: asd
  url: ${PAYMENT_INTEGRATION_URL:http://localhost:9090/api/v1/payment/}

jwt:
  header: Authorization
  secret: mobest1an
  expirationTime: 21

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      atomikos: DEBUG
