CREATE TABLE user_entity
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255),
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_entity PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user_entity FOREIGN KEY (user_id) REFERENCES user_entity (id);
